/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoVeterinaria;

/**
 *
 * @author Khervi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opCliente = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        opMascota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opHistorial = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        opFactura = new javax.swing.JMenuItem();
        opDetFact = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        opProducto = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Veterinaria Entre Patas");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jMenuBar1.setName(""); // NOI18N

        jMenu2.setText("Cliente");

        opCliente.setText("registrarCliente");
        opCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClienteActionPerformed(evt);
            }
        });
        jMenu2.add(opCliente);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Mascota");

        opMascota.setText("Registrar Mascota");
        opMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMascotaActionPerformed(evt);
            }
        });
        jMenu9.add(opMascota);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("Historial");

        opHistorial.setText("registrar Historial");
        opHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHistorialActionPerformed(evt);
            }
        });
        jMenu3.add(opHistorial);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");

        opFactura.setText("Factura");
        opFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(opFactura);

        opDetFact.setText("Detalle Factura");
        opDetFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDetFactActionPerformed(evt);
            }
        });
        jMenu4.add(opDetFact);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Producto");

        opProducto.setText("Productos");
        opProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProductoActionPerformed(evt);
            }
        });
        jMenu5.add(opProducto);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClienteActionPerformed
        Cliente ventana=new Cliente();
        escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_opClienteActionPerformed

    private void opHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHistorialActionPerformed
        // TODO add your handling code here:
        Historial ventHis=new Historial();
        escritorio.add(ventHis);
        ventHis.show();
    }//GEN-LAST:event_opHistorialActionPerformed

    private void opProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProductoActionPerformed
        // TODO add your handling code here:
        
        Productos Pro=new Productos();
        escritorio.add(Pro);
        Pro.show();
        
    }//GEN-LAST:event_opProductoActionPerformed

    private void opFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opFacturaActionPerformed
        // TODO add your handling code here:
        
        Factura fac=new Factura();
        escritorio.add(fac);
        fac.show();
        
    }//GEN-LAST:event_opFacturaActionPerformed

    private void opMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMascotaActionPerformed
        // TODO add your handling code here:
        
        Mascota mas=new Mascota();
        escritorio.add(mas);
        mas.show();
    }//GEN-LAST:event_opMascotaActionPerformed

    private void opDetFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDetFactActionPerformed
        // TODO add your handling code here:
        
        DetalleFactura det=new DetalleFactura();
        escritorio.add(det);
        det.show();
    }//GEN-LAST:event_opDetFactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem opCliente;
    private javax.swing.JMenuItem opDetFact;
    private javax.swing.JMenuItem opFactura;
    private javax.swing.JMenuItem opHistorial;
    private javax.swing.JMenuItem opMascota;
    private javax.swing.JMenuItem opProducto;
    // End of variables declaration//GEN-END:variables
}
